cards_data: ./cards.json
# cards_data: /Users/sml/git/cr-api-data-process/docs/json/cards.json
cards_data_url: https://royaleapi.github.io/cr-api-data/json/cards.json
src_dir: ./src
spells_dir: ./card-src-236x300
output_png24_dir: ./cards
output_png8_dir: ./cards-png8
output_png24_gold_dir: ./cards-gold
output_png8_gold_dir: ./cards-gold-png8
output_png24_elixir_dir: ./cards-elixir
output_png8_elixir_dir: ./cards-elixir-png8
working_dir: ./
raw_dir: ./cards-raw
cards:
  ui_spells_sprite_00: sparky
  ui_spells_sprite_01: zap
  ui_spells_sprite_02: wizard
  ui_spells_valkyrie-0: valkyrie
  ui_spells_sprite_04: tornado
  ui_spells_sprite_05: tombstone
  ui_spells_sprite_06: three-musketeers
  ui_spells_sprite_07: ice-spirit
  ui_spells_sprite_08: skeletons
  ui_spells_sprite_09: guards
  ui_spells_sprite_10: skeleton-army
  ui_spells_sprite_11: skeleton-barrel
  ui_spells_sprite_12: gold-3
  ui_spells_sprite_13: gold-2
  ui_spells_sprite_14: gold-1
  ui_spells_sprite_15: gems-6
  ui_spells_sprite_16: gems-5
  ui_spells_sprite_17: gems-4
  ui_spells_sprite_18: gems-3
  ui_spells_sprite_19: gems-2
  ui_spells_sprite_20: gems-1
  royal-giant-2022-09: royal-giant
  ui_spells_sprite_22: knight
  ui_spells_sprite_23: archers
  ui_spells_sprite_24: rocket
  ui_spells_sprite_25: lumberjack
  ui_spells_sprite_26: rage
  ui_spells_sprite_27: princess
  ui_spells_sprite_28: prince
  ui_spells_sprite_29: poison
  ui_spells_sprite_30: pekka
  ui_spells_sprite_31: arrows
  ui_spells_sprite_32: musketeer
  ui_spells_sprite_33: minion-horde
  ui_spells_sprite_34: minions
  ui_spell_mini_pekka: mini-pekka
  ui_spells_sprite_36: miner
  ui_spells_sprite_37: mega-minion
  ui_spells_sprite_38: mega-knight
  ui_spells_sprite_39: the-log
  ui_spells_sprite_40: lightning
  ui_spells_sprite_41: lava-hound
  ui_spells_sprite_42: inferno-dragon
  ui_spells_sprite_43: ice-wizard
  ui_spells_sprite_44: ice-golem
  ui_spells_sprite_45: hog-rider
  ui_spells_sprite_46: heal
  ui_spells_sprite_47: graveyard
  ui_spells_sprite_48: gold
  ui_spells_sprite_49: goblins
  ui_spells_sprite_50: dart-goblin
  ui_spells_sprite_51: goblin-gang
  ui_spells_sprite_52: goblin-barrel
  ui_spells_sprite_53: spear-goblins
  ui_spell_giant_skeleton: giant-skeleton
  ui_spells_sprite_55: giant
  ui_spells_sprite_56: gems
  ui_spells_sprite_57: freeze
  flying-machine: flying-machine
  ui_spells_sprite_59: furnace
  ui_spells_sprite_60: fire-spirit
  ui_spells_sprite_61: fireball
  ui_spells_sprite_62: executioner
  ui_spells_sprite_63: electro-wizard
  night-witch-card: night-witch
  ui_spells_sprite_65: dark-prince
  ui_spells_sprite_66: clone
  ui_spell_witch: witch
  ui_spells_sprite_68: golem
  ui_spells_sprite_69: balloon
  ui_spells_sprite_70: cannon
  ui_spells_sprite_71: cannon-cart
  ui_spells_sprite_72: x-bow
  ui_spells_sprite_73: inferno-tower
  ui_spells_sprite_74: elixir-collector
  ui_spells_sprite_75: bowler
  ui_spells_sprite_76: bomber
  ui_spells_sprite_77: bomb-tower
  ui_spells_sprite_78: battle-ram
  ui_spells_sprite_79: bats
  ui_spells_sprite_80: barbarians
  ui_spells_sprite_81: barbarian-hut
  ui_spells_sprite_82: bandit
  ui_spells_sprite_83: baby-dragon
  ui_spells_sprite_84: elite-barbarians
  ui_spells_sprite_85: empty-1
  ui_spells_sprite_86: empty-2
  ui_spells_sprite_87: soon
  ui_spells_sprite_88: mirror
  tesla: tesla
  mortar: mortar
  goblin_hut: goblin-hut
  ui_spell_ghost: royal-ghost
  ui_spell_hunter: hunter
  ui_spell_zappies: zappies
  ui_spell_magic_archer: magic-archer
  ui_spell_barb_barrel: barbarian-barrel
  ui_spell_rascals: rascals
  ui_spell_royal_hogs: royal-hogs
  ui_spell_giant_snowball: giant-snowball
  ui_spell_royal_recruits: royal-recruits
  goblin_giant: goblin-giant
  ui_spell_electro_dragon: electro-dragon
  ui_spell_ram_rider: ram-rider
  ui_spell_wall_breakers: wall-breakers
  ui_spell_earthquake: earthquake
  ui_spell_goblin_cage: goblin-cage
  ui_fisherman_framed: fisherman
  elixir_golem: elixir-golem
  battle_healer_card_image: battle-healer
  ui_spell_firecracker: firecracker
  royal_delivery_card_image: royal-delivery
  ui_spell_heal_spirit: heal-spirit
  ui_spell_skeleton_dragon: skeleton-dragons
  ui_spell_electro_giant: electro-giant
  ui_spell_electro_spirit: electro-spirit
  ui_spell_mother_witch: mother-witch
  ui_spell_goblin_drill: goblin-drill
  ui_spell_skeleton_king: skeleton-king
  ui_spell_archer_queen: archer-queen
  ui_spell_golden_knight: golden-knight
  ui_spell_super_lava_hound: super-lava-hound
  ui_spell_mighty_miner: mighty-miner
  ui_spell_super_witch: super-witch
  ui_spell_super_mini_pekka: super-mini-pekka
  barbarian-launcher-236x300: barbarian-launcher
  phoenix: phoenix
  monk: monk
